export const data = [
    {
        id: "mujeres",
        name: "Que ves cuando me/te ves?",
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Mujeres/Mujeres1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Mujeres/Mujeres2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Mujeres/Mujeres3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Mujeres/Mujeres4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Mujeres/Mujeres5.jpg',
        description: 'Esta serie de cuatro mujeres nació de pensar que muchas veces nos armamos de ideas o preconceptos sobre las personas sin detenernos a saber realmente cómo son o qué están atravesando.\nLo que pensamos del otro está directamente influenciado por lo que nosotros estamos atravesando en ese momento.\nEntonces, la propuesta de la obra sobre espejo es animarse a interpretarla según nuestro propio reflejo, y así invitarte a que te preguntes… Qué ves cuando me/te ves?',
        englishDescription: 'This series of four women was born from thinking that many times we build ideas or preconceived notions about people without stopping to know really how they are or what they are going through.\nWhat we think about the other is directly influenced by what we are going through at that moment.\nThen, the proposal of the artwork on the mirror is to animate yourself to interpret it according to your own reflection, and so invite you to ask yourself… What do you see when you see me/you?',
        technique: 'Acrílico y aerosol',
        englishTechnique: 'Acrylic and spray paint',
        price: 60000,
        price4: 200000,
        priceMirror: 90000,
        price4Mirror: 320000,
        // priceUsd: 0,
        size: '20 x 20 cm',
        sizeMirror: '30 x 30 cm',
        dispo: true,
        small: false
    },
    {
        id: 'raices',
        name: 'Raíces',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Raices/Raices1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Raices/Raices2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Raices/Raices3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Raices/Raices4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Raices/Raices5.jpg',
        description: 'Raíces es una obra que nació con ganas de hacer una obra en colores neutros y jugar con distintas técnicas cuando justo por trabajo me tocó viajar a General Roca, Río Negro.\nRecorriendo la Ruta 22 me sorprendieron sus paisajes y la forma en que sus valles cortaban el cielo hizo que al regresar volcara toda la inspiracion en la tela.\nLa presenté en Palacio Cabrera donde los visitantes destacaban su delicadeza y el efecto estéreo logrado.',
        englishDescription: 'Raíces is an artwork that was born with the desire to make a work in neutral colors and play with different techniques when I was traveling to General Roca, Río Negro.\nWhile traveling on Route 22, I was surprised by its landscapes and the way its valleys cut the sky, which made me return to the canvas with all the inspiration.\nI presented it at Palacio Cabrera where the visitors highlighted its delicacy and the stereo effect achieved.',
        technique: 'Acrílicos, pintura asfáltica, piedras de cuarzo y aerosoles.',
        englishTechnique: 'Acrylics, asphalt paint, quartz stones and aerosols.',
        price: 250000,
        // priceUsd: 0,
        size: '120 x 60 cm',
        dispo: true,
        small: false
    },
    {
        id: 'borrasca',
        name: 'Borrasca',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Borrasca/Borrasca1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Borrasca/Borrasca2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Borrasca/Borrasca3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Borrasca/Borrasca4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Borrasca/Borrasca5.jpg',
        description: 'A ésta obra la bautizó mi papá, cosa especial para mí en éstos momentos en que venimos compartiendo mucho tiempo porque anda peleando su propia tormenta.\nEn el momento en que la vió, comentó que le representó ese instante en que la proa del barco choca contra la ola en plena tormenta marina salpicando gotas de mar al cielo.\nY me pareció, primero un honor que él bautizara a una de mis obras, y segundo una hermosa interpretación.\nBorrasca es ideal para poner sobre una cama o un sillon por su formato horizontal.\nEstá hecha en color azul plomo y plateado con texturas logradas con pasta y piedras de cuarzo.',
        englishDescription: 'My dad named this piece, which is something very special to me right now, as we’ve been spending a lot of time together while he faces his own storm.\nWhen he saw it, he said it represented that moment when the bow of a ship crashes into a wave in the middle of a storm at sea, splashing drops of water up into the sky.\nTo me, it felt, first, like an honor that he would name one of my works, and second, like a beautiful interpretation.\nBorrasca is ideal to place above a bed or a sofa thanks to its horizontal format.\nIt is painted in lead blue and silver tones, with textures created using paste and quartz stones.',
        technique: 'Acrílicos, pasta de moldear y piedras de cuarzo.',
        englishTechnique: 'Acrylics, moldable paste and quartz stones.',
        price: 200000,
        // priceUsd: 0,
        size: '120 x 50 cm',
        dispo: true,
        small: false
    },
    {
        id: 'fusion',
        name: 'Fusión',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Fusion/Fusion1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Fusion/Fusion2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Fusion/Fusion3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Fusion/Fusion4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Fusion/Fusion5.jpg',
        description: 'Fusión es una obra que nació queriendo experimentar con materiales diversos en colores neutros.\n\nElegí trabajar con aerosoles, tintas, pintura asfáltica y el brillo de las hojas de oro que siempre me gusta usar para aportar distinción a las obras.\n\nMe llevó mucho tiempo soltar esta obra porque siempre encontraba algo más para aportarle, un nuevo contraste, un detalle, un poco más de dorado.\n\nPero ahora sí está completa.. y la suelto repleta de linda energía en la tela, toda la pasión y diversión que sentí al crearla.\n\nEs una obra que me encantaría tener en mi casa, pero que está lista para seguir su camino en otras manos llenando de su energía otros espacios.',
        englishDescription: 'Fusion is a piece that was born from a desire to experiment with different materials in neutral colors.\n\nI chose to work with spray paint, inks, asphalt paint, and the shine of gold leaf, which I always love to use to bring distinction to my works.\n\nIt took me a long time to let go of this piece because I kept finding something more to add—a new contrast, a detail, a touch more of gold.\n\nBut now it is complete... and I release it filled with beautiful energy on the canvas, with all the passion and joy I felt while creating it.\n\nIt is a work I would love to keep in my home, but it is ready to continue its journey in other hands, filling new spaces with its energy.',
        technique: 'Aerosoles, tintas, pintura asfáltica, acrílico y dorado a la hoja.',
        englishTechnique: 'Aerosols, paints, asphalt paint, acrylic and gold leaf.',
        price: 200000,
        // priceUsd: 0,
        size: '120 x 50 cm',
        dispo: true,
        small: false
    },
    {
        id: 'crepusculo',
        name: 'Crepúsculo',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Crepusculo/Crepusculo1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Crepusculo/Crepusculo2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Crepusculo/Crepusculo3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Crepusculo/Crepusculo4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Crepusculo/Crepusculo5.jpg',
        description: 'A vos también te pasa que cuando ves el cielo en esa hora en que el sol se está escondiendo de repente sentís como algo hipnótico que te gustaría que ese instante fuera eterno?.\nA mí me sucede estando en la playa, en el horizonte de la autopista cuando voy manejando, en la ventana de casa cuando está cerrando el día... \nBueno, ésta obra nació queriendo plasmar los tonos del atardecer. Y como pasa siempre que la obra cobra vida y uno acompaña el proceso, resultó transmitir mucha pasión y energía. \nLa fusión de los tonos es muy poderosa y los detalles en dorado aportan un toque de sofisticación.',
        englishDescription: "Does it also happen to you that when you look at the sky at that hour when the sun is setting, you suddenly feel something hypnotic, wishing that moment could last forever?\nIt happens to me at the beach, on the highway horizon while driving, or at my home window when the day is coming to a close...\nWell, this artwork was born from a desire to capture the tones of the sunset. And, as always happens when the artwork comes to life and you go along with the process, it ended up conveying so much passion and energy.\nThe blend of tones is incredibly powerful, and the golden details add a touch of sophistication.",
        technique: "Acrílicos y pasta de relieve.",
        englishTechnique: 'Acrylics and relief paste.',
        price: 200000,
        // priceUsd: 0,
        size: '60 x 80 cm',
        dispo: true,
        small: false
    },
    {
        id: "costa",
        name:"Costa",
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Costa/Costa-mockup.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Costa/Costa2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Costa/Costa3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Costa/Costa4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Costa/costa-blanco.jpg',
        description: 'Mi pasión por el mar y sus colores me motivó a realizar esta obra en formato horizontal que se adapta a cualquier ambiente, ya sea sobre algún sillón o una cama.\nEl fluir de los materiales y los relieves convierten a ésta obra en una pieza única.',
        englishDescription: "My passion for the sea and its colors inspired me to create this horizontal piece that fits perfectly in any space, whether above a sofa or a bed.\nThe flow of the materials and the textures make this artwork a truly unique piece.",
        technique: "Acrílicos, pintura asfáltica y piedras naturales de cuarzo.",
        englishTechnique: 'Acrylics, asphalt paint, and natural quartz stones.',
        price: 300000,
        // priceUsd: 0,
        size: '120 x 80cm',
        dispo: true,
        small: false
    },
    {
        id: 'bosque-dorado',
        name: "Bosque dorado",
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Bosque/Bosque-Mockup.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Bosque/Bosque1.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Bosque/Bosque2.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Bosque/Bosque3.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Bosque/Bosque4.jpg',
        description: 'Todas las veces que voy a Villa Gesell paso aunque sea un rato en el Pinar del Norte con mi cámara porque el bosque siempre me regala fotos increíbles.\nÉste año, paseando con mis hijos, nos perdimos entre plantaciones que dejaban pasar el reflejo del sol como haces de luz.\nObviamente, eso se transformó en inspiración inmediata para hacer una obra abstracta en color verde y detalles dorados que, con el reflejo del sol o la luz, transmite la misma sensación que tuve dentro del bosque.\nEl resultado es una obra muy delicada y dinámica para traer vida a cualquier espacio.',
        englishDescription: "Every time I go to Villa Gesell, I always spend at least a little while in the Pinar del Norte with my camera, because the forest always offers me incredible photos.\nThis year, while walking with my children, we got lost among plantations where sunlight filtered through like beams of light.\nNaturally, that became immediate inspiration to create an abstract artwork in green with golden details that, with sunlight or any light reflection, conveys the same feeling I had inside the forest.\nThe result is a very delicate and dynamic piece that brings life to any space.",
        technique: "Pasta de relieve, acrílicos y laminas de oro.",
        englishTechnique: 'Relief paste, acrylics and gold leafs.',
        price: 200000,
        // priceUsd: 0,
        size: '60 x 80 cm',
        dispo: true,
        small: false
    },
    {
        id: "alma",
        name:"Alma",
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Alma/Alma-mockup.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Alma/Alma2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Alma/Alma3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Alma/Alma4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Alma/Alma-FondoBlanco.jpg',
        description: 'Esta obra es un nuevo retrato abstracto que forma parte de la serie de mujeres que transmiten fortaleza, que emergen de la profundidad de los sentidos y que iluminan con su luz propia.\nALMA es una obra en formato mediano muy delicada y a la vez poderosa y que con el juego de la luz produce unos reflejos que aportan significado al propósito de la obra.',
        englishDescription: "This piece is a new abstract portrait that is part of the series of women who convey strength, who emerge from the depths of the senses, and who shine with their own light.\nALMA is a medium-sized artwork that is both delicate and powerful, and through the play of light, it creates reflections that add meaning to the purpose of the piece.",
        technique: "Pasta de relieve, acrílicos y laminas de plata.",
        englishTechnique: 'Relief paste, acrylics and silver leafs.',
        price: 100000,
        // priceUsd: 0,
        size: '30 x 50 cm',
        dispo: true,
        small: false
    },
    {
        id: "marea",
        name:"Marea",
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Marea/marea-mockup.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Marea/marea2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Marea/marea3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Marea/marea4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Marea/Marea-Blanco.jpg',
        description: 'Jugar con materiales y texturas para crear obras marinas me apasiona. Para traer siempre nuevas propuestas marinas esta vez hice un díptico que al verlo automáticamente transporta al mar.\nSon ideales para poner en algún recibidor o un rincón especial de tu casa. Sobre todo, que jugando con el espacio libre entre las obras, podés cubrir más o menos espacio.',
        englishDescription: "Playing with materials and textures to create ocean-inspired artworks is something I'm passionate about. To keep bringing fresh marine-inspired pieces, this time I created a diptych that instantly transports you to the sea.\nThey’re ideal for placing in an entryway or a special corner of your home. Especially because, by adjusting the space between the pieces, you can cover more or less area.",
        technique: "Pasta de relieve, piedras naturales de cuarzo y acrílicos.",
        englishTechnique: 'Relief paste, natural quartz stones and acrylics.',
        price: 200000,
        // priceUsd: 0,
        size: 'Individual: 30 x 50 cm',
        triptico: "65 x 50",
        dispo: true,
        small: false
    },
    {
        id: 'misterio',
        name: 'Misterio',
        principalImage:"https://www.artesust.com.ar/ImageSabrinaRecortadas/Misterio/Misterio1.jpg",
        secondImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Misterio/Misterio2.jpg",
        thirdImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Misterio/Misterio3.jpg",
        fourthImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Misterio/Misterio4.jpg",
        fifthImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Misterio/Misterio5.jpg",
        description:"Hace unos días, después de largas horas de lluvia, el atardecer nos regaló un cielo en distintos tonos violeta que parecía pintado.\nObviamente que semejante espectáculo me despertó un gran deseo de poner manos a la obra aplicando esos tonos. En el proceso decidí incluir texturas y detalles en dorado que le aportaron un toque de elegancia y delicadeza, y que también podría representar el reflejo del sol que se escondía tras las espesas nubes.\nFue un proceso hermoso, porque si bien no son colores que yo suelo utilizar, la conexión con la naturaleza fue natural e inmediata.",
        englishDescription: "A few days ago, after long hours of rain, the sunset gifted us a sky in various shades of violet that looked like it had been painted.\nObviously, such a spectacle sparked a great desire in me to get to work and apply those tones. During the process, I decided to include textures and golden details that added a touch of elegance and delicacy, which could also represent the reflection of the sun hiding behind the thick clouds.\nIt was a beautiful process because, although these are not colors I usually use, the connection with nature was natural and immediate.",
        technique: "Acrílicos y relieves.",
        englishTechnique: "Acrylics and relief.",
        price: 150000,
        // priceUsd: 0,
        size: '50 x 60 cm',
        dispo: true,
        small: false
    },
    {
        id: 'triptico-marino',
        name: 'Triptico Marino',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/TripticoMarino/MockUpTriptico.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/TripticoMarino/TripticoA.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/TripticoMarino/TripticoB.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/TripticoMarino/TripticoC.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/TripticoMarino/TripticoCompleto.jpg',
        description: 'Movimiento, dinamismo, libertad, bravura... Imaginate entrar a tu casa y todos los días poder encontrarte con esas sensaciones. Es ideal para darle distinción y personalidad a un recibidor, o colocarlo sobre una cómoda en el living donde poder verlo mientras tomas una bebida o un rico café y te relajas al final del día. Lo mágico del arte es poder transportarte por un instante a otro lugar y disfrutar.',
        englishDescription: "Movement, dynamism, freedom, bravery... Imagine coming home and being greeted by these sensations every day. It's perfect for adding distinction and personality to an entryway or placing it on a console table in the living room, where you can admire it while enjoying a drink or a delicious coffee as you unwind at the end of the day. The magic of art lies in its ability to transport you, even for a moment, to another place and let you enjoy the experience.",
        technique: "Acrílicos y relieves.",
        englishTechnique: 'Acrylics and relief.',
        price: 130000,
        // priceUsd: 0,
        size: 'Individual: 18 x 24 cm',
        triptico: "54 x 24",
        dispo: true,
        small: false
    },
    {
        id: 'esencia',
        name: 'Esencia',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esencia/Esencia1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esencia/Esencia2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esencia/Esencia3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esencia/Esencia4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esencia/Esencia5.jpg',
        description: 'Siento que ésta obra me representa, que volqué en la tela mi esencia. \nEn la vorágine de la vida si me tomo un momento para cerrar los ojos y me dejo llevar, veo mi silueta representada en pinceladas; soy arte, soy creación, la artista de mi propia vida. Y en ese contexto siento paz, calma y serenidad.\nLa obra está presentada con marco flotante de Kiri en color negro.\nEstá expuesta en la muestra Percepciones en Galería Zero168.',
        englishDescription: "I feel that this artwork represents me, that I poured my essence onto the canvas.\nIn the whirlwind of life, if I take a moment to close my eyes and let myself go, I see my silhouette represented in brushstrokes; I am art, I am creation, the artist of my own life. And in that context, I feel peace, calm, and serenity.\nThe artwork is presented in a black kiri floating frame.\nIt is exhibited in the Percepciones show at Gallery Zero618.",
        technique: "Acrílicos.",
        englishTechnique: 'Acrylics.',
        price: 200000,
        // priceUsd: 0,
        size: '60 x 80 cm',
        dispo: false,
        small: false
    }, {
        id: 'percepcion-dos',
        name: 'Percepcion 2',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion2/Percepcion2-1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion2/Percepcion2-2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion2/Percepcion2-3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion2/Percepcion2-4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion2/Percepcion2-5.jpg',
        description: 'Ésta obra es la tercera que creo de la serie Percepción, aunque cada una tiene una magia especial. En este caso, las texturas y reflejos en su tamaño resultan impactantes.\n\nLa importancia de entregarse a las sensaciones y a la forma en que la obra nos atraviesa.\nDonde algunos pueden ver y sentir la inmersión hacia el fondo, otros como yo podemos ver el impulso hacia el reflejo, la luz, la cima.\nÉsta obra invita a despertar los sentidos, apreciar los relieves, sentir la textura, ver la luz y la sombra.\nEstá presentada en marco flotante de Kiri negro.\nLa obra está siendo expuesta en Palacio Barolo durante el mes de Octubre 2024.',
        englishDescription: "This is the third piece I’ve created in the Percepción series, although each one has its own special magic. In this case, the textures and reflections, in its size, are striking.\nThe importance lies in surrendering to the sensations and the way the artwork moves through us.\nWhere some may see and feel an immersion into the depths, others, like me, may see the drive toward the reflection, the light, the peak.\nThis artwork invites you to awaken your senses, appreciate the reliefs, feel the texture, and observe the interplay of light and shadow.\nIt is presented in a black kiri floating frame.\nThe artwork is being exhibited at Palacio Barolo during October 2024.",
        technique: "Acrílicos y pasta de relieve.",
        englishTechnique: 'Acrylics and relief paste.',
        price: 500000,
        // priceUsd: 0,
        size: '80 x 120 cm',
        dispo: true,
        small: false
    }, {
        id: 'aurora',
        name: 'Aurora',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Aurora/Aurora1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Aurora/Aurora2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Aurora/Aurora3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Aurora/Aurora4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Aurora/Aurora5.jpg',
        description: 'Inspirada en los primeros rayos de sol que interrumpen la oscuridad de la noche para dar comienzo a un nuevo día, ésta obra poderosa juega con relieves, reflejos y brillo. \nEl negro es la ausencia de luz, y a la vez es la mezcla de todos los colores; transmite poder, formalidad, misterio, fuerza... Y si al negro lo cortamos con el dorado, que representa la luz, conseguimos un balance muy poderoso e interesante.\nLa obra está presentada con marco flotante de kiri color negro.\nEstá siendo expuesta en Palacio Barolo durante el mes de Octubre 2024.',
        englishDescription: "Inspired by the first rays of sunlight that break through the darkness of the night to start a new day, this powerful piece plays with reliefs, reflections, and shine.\nBlack is the absence of light, yet it is also the combination of all colors; it conveys power, formality, mystery, strength... And if we cut through the black with gold, which represents light, we achieve a very powerful and interesting balance.\nThe artwork is presented in a black kiri floating frame.\nit is being exhibited at Palacio Barolo during October 2024.",
        technique: 'Acrílicos, texturas y laminas de oro.',
        englishTechnique: "Acrylics, textures, and gold leaf.",
        price: 450000,
        // priceUsd: 0,
        size: '80 x 120 cm',
        dispo: true,
        small: false
    }, {
        id: "luz-de-luna",
        name: 'Luz de luna',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LuzdeLuna/LuzLuna1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LuzdeLuna/LuzLuna2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LuzdeLuna/LuzLuna3.jpg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LuzdeLuna/LuzLuna4.jpg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LuzdeLuna/LuzLuna5.jpg',
        description: 'Una de las cosas que más me gustan, además del mar, es la Luna. Me apasiona seguir sus cambios y los momentos en que se la ve salir gigante de atrás de los edificios.\nEn esta fascinación me inspiré para crear ésta obra que combina lo abstracto y lo figurativo en colores neutros que se adaptan a cualquier espacio.\nLa obra tiene marco flotante de Kiri color negro.\nParticipó de la muestra Percepciones en Galería Zero168.',
        englishDescription: "One of the things I love most, besides the sea, is the Moon. I am passionate about observing its changes and the moments when it rises, enormous, behind the buildings.\nThis fascination inspired me to create this artwork that combines the abstract and the figurative in neutral colors that adapt to any space.\nThe artwork has a black kiri floating frame.\nIt participated in the Percepciones show at Gallery Zero618.",
        technique: 'Acrílicos y relieves.',
        englishTechnique: "Acrylics and reliefs.",
        price: 450000,
        // priceUsd: 0,
        size: '80 x 120 cm',
        dispo: true,
        small: false
    },
    {
        id: 'turmalina',
        name: 'Turmalina',
        principalImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Turmalina/Turmalina1.jpg",
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Turmalina/Turmalina2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Turmalina/Turmalina3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Turmalina/Turmalina4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Turmalina/Turmalina5.jpeg',
        description: 'Inspirada en la piedra tan protectora, hice ésta obra poderosa que juega con relieves, reflejos y brillo. \n\n El negro es la ausencia de luz, y a la vez es la mezcla de todos los colores; transmite poder, formalidad, misterio, fuerza... Y si al negro lo cortamos con el dorado, que representa la luz, conseguimos un balance muy poderoso e interesante.\n Obra presentada con marco flotante de kiri color negro.\nTurmalina fue expuesta en la muestra Percepciones y en Galería Zero618.',
        englishDescription: "Inspired by the protective nature of stone, I created this powerful piece that plays with reliefs, reflections, and shine. Black is the absence of light, yet it is also the combination of all colors; it conveys power, formality, mystery, strength... And when we cut through black with gold, which represents light, we achieve a very powerful and interesting balance.\n Piece presented in a black Kiri floating frame.\nTurmalina was exhibited at the Percepciones show at Gallery Zero618.",
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',
        price: 200000,
        // priceUsd: 20,
        size: '50 x 60 cm',
        dispo: true,
        small: false
    },
    {
        id: 'atardecer',
        name: 'Atardecer',
        principalImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Atardecer/Atardecer1.jpg",
        secondImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Atardecer/Atardecer2.jpeg",
        thirdImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Atardecer/atardecer3.jpeg",
        fifthImage: "https://www.artesust.com.ar/ImageSabrinaRecortadas/Atardecer/Atardecer5.jpeg",
        description: 'Inspirada en la fuerza del atardecer fui creando ésta pequeña obra para traer un poco de esa poderosa sensación al interior del hogar.',
        englishDescription: "Inspired by the strength of the sunset, I created this small piece to bring a bit of that powerful sensation into the home. \nDue to its size, it can be placed on a shelf or desk, or hung from its floating frame.",
        technique: 'Juego de textura y degradé.',
        englishTechnique: 'Texture and gradient.',
        // price: 250000,
        // priceUsd: 20,
        size: '20 x 20 cm',
        dispo: false,
        small: false
    },
    {
        id: 'profundidad',
        name: 'Profundidad',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Profundidad/Profundidad1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Profundidad/Profundidad2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Profundidad/Profundidad3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Profundidad/Profundidad4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Profundidad/Profundidad5.jpeg',
        description: 'Bauticé a ésta obra con su nombre porque como dice Shakespeare "Allí donde el agua alcanza su mayor profundidad se mantiene más en calma". \nLa realicé en un momento de mucha instrospección y sus colores fríos fundidos uno con el otro lo representan logrando un impacto muy especial. \n Presentado en marco flotante de Kiri color natural.\nProfundidad fue expuesta en Cultura Viva y en la muestra Percepciones en Galería Zero618.',
        englishDescription: "I named this piece after Shakespeare’s quote, 'In the deepest water, the calmest stillness resides.' \nI created it during a time of deep introspection, and its cool colors blended into one another represent that, achieving a very special impact. \nPresented in a natural Kiri floating frame.\nProfundidad was exhibited at Cultura Viva and at the Percepciones exhibition at Gallery Zero618.",
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',
        price: 400000,
        // priceUsd: 20,
        size: '100 x 120 cm',
        dispo: true,
        small: false
    },
    {
        id: 'eternidad',
        name: 'Eternidad',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Eternidad/Eternidad1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Eternidad/Eternidad2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Eternidad/Eternidad3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Eternidad/Eternidad4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Eternidad/Eternidad5.jpeg',
        description: 'Al momento de hacer ésta obra me inspiré en la vida, la tierra, lo eterno.\nPresentada en marco flotante de Kiri color natural.\nEternidad fue expuesta en la muestra Percepciones en Galería Zero618.',
        englishDescription: "When creating this piece, I was inspired by life, the earth, and the eternal.\n Presented in a natural Kiri floating frame.\nEternidad was exhibited at the Perceptions show at Gallery Zero618.",
        technique: 'Técnica mixta, relieves, acrílicos y pintura asfáltica.',
        englishTechnique: "Mixed techniques, reliefs, acrylics, and asphalt paint.",
        price: 200000,
        // priceUsd: 20,
        size: '60 x 40 cm',
        dispo: true,
        small: false
    },
    {
        id: 'ola-magnetica',
        name: 'La Ola Magnetica',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica5.jpeg',
        description: 'Quién no estuvo alguna vez en el mar y tuvo la oportunidad de ver ese rulo perfecto que se forma en la ola antes de romper con toda su bravura?\nEn esta obra jugué con la textura y mis colores favoritos para transmitir esa hermosa sensación mezcla de adrenalina y admiración.\nPresentado en marco flotante de Kiri color negro.\nLa Ola Magnética fue expuesta en la muestra Percepciones en Galería Zero618.',
        englishDescription: "Who hasn't been to the sea at some point and had the chance to see that perfect curl that forms in the wave before it crashes with all its might?\nIn this piece, I played with texture and my favorite colors to convey that beautiful sensation of a mix of adrenaline and admiration.\n Presented in a black Kiri floating frame.\nLa Ola Magnética was exhibited in the Percepciones show at Gallery Zero618.",
        technique: 'Realizada con pasta de modelar y acrílicos.',
        englishTechnique: "Made with modeling paste and acrylics.",
        price: 200000,
        // priceUsd: 20,
        size: '40 x 60 cm',
        dispo: true,
        small: false
    },
    {
        id: 'ritmo',
        name: 'Ritmo',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Ritmo/Ritmo1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Ritmo/Ritmo2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Ritmo/Ritmo3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Ritmo/Ritmo4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Ritmo/Ritmo5.jpeg',
        description: 'Una más de las obras en pequeño formato que me gusta hacer para destacar espacios. \nLa obra RITMO es una expresión de colores neutros y brillos que combinan y armonizan unos con otros. Brinda originalidad y distinción a cualquier espacio.\n Empotrado en marco flotante de Kiri color natural.\nRitmos fue expuesta en Palacio Barolo.',
        englishDescription: "Another one of the small-format pieces I enjoy creating to highlight spaces. \nThe piece RITMO is an expression of neutral colors and shines that blend and harmonize with one another. It adds originality and distinction to any space. \n Set in a natural Kiri floating frame.\nRitmos was exhibited at Palacio Barolo.",
        technique: 'Acrílicos.',
        englishTechnique: "Acrylics.",
        // price: 250000,
        // priceUsd: 20,
        size: '20 x 20 cm',
        dispo: false,
        small: false
    },
    {
        id: 'cambio',
        name: 'El Cambio',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElCambio/ElCambio1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElCambio/ElCambio2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElCambio/ElCambio3.jpeg',
        // fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElCambio/ElCambio4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElCambio/ElCambio5.jpeg',
        description: 'Ésta obra la hice en un momento de cambio en mi vida, donde se abrían nuevas posibilidades, nuevos caminos, aparecían nuevas opciones y tomaba elecciones importantes.\nLo que a simple vista son sólo líneas, en realidad representan caminos cruzados, conexiones, uniones y opciones. Realizado en los colores con los que más disfruto trabajar, el resultado es un hermoso caos ordenado. \n Está empotrada en marco flotante de Kiri natural.\nEl Cambio fue expuesta en la muestra Percepciones en Galería Zero618.',
        englishDescription: "I created this piece during a time of change in my life, when new possibilities were opening up, new paths were emerging, and I was making important choices. \n What may seem like mere lines at first glance actually represent crossed paths, connections, unions, and options. Made with the colors I enjoy working with the most, the result is a beautiful, ordered chaos.\n It is set in a natural Kiri floating frame.\nEl Cambio was exhibited in the Percepciones show at Gallery Zero618.",
        technique: 'Acrílico.',
        englishTechnique: "Acrylics.",
        price: 300000,
        // priceUsd: 20,
        size: '80 x 120 cm',
        dispo: false,
        small: false
    },
    {
        id: 'trazos',
        name: 'Trazos',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Trazos/Trazos1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Trazos/Trazos2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Trazos/Trazos3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Trazos/Trazos4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Trazos/Trazos5.jpeg',
        description: 'Tríptico en colores neutros. La simpleza de las líneas y sus colores dan un toque de estilo a cualquier ambiente.\nPueden decorar de forma individual o en conjunto. \nEstán presentados en marco flotante de Kiri color natural.\nTrazos fue expuesta en Palacio Barolo.',
        englishDescription: "Triptych in neutral colors. The simplicity of the lines and their colors add a touch of style to any environment. \nThey can be displayed individually or as a set. \nThey are presented in a natural Kiri floating frame.\nTrazos was exhibited at Palacio Barolo.",
        technique: 'Acrílico.',
        englishTechnique: "Acrylics.",
        price: 200000,
        // priceUsd: 20,
        size: '30 x 40 cm',
        dispo: true,
        small: false
    },
    {
        id: 'arena-dorada',
        name: 'Arena Dorada',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada5.jpeg',
        description: 'Una obra pequeña para apoyar sobre un recibidor o colgarlo en algún espacio reducido que se busque destacar.\nEl dorado representa una alta vibración que llena de energía a la persona que lo observa. Es un símbolo de poder y fortaleza.\nEnmarcado en Kiri de color natural\nArena Dorada fue expuesta en Palacio Barolo.',
        englishDescription: "A small piece to place on a console table or hang in a compact space that you want to highlight.\nThe gold represents a high vibration that fills the person who observes it with energy. It is a symbol of power and strength.\n Framed in natural Kiri.\nArena Dorada was exhibited at Palacio Barolo.",
        technique: 'Relieves, acrílico dorado y pintura asfáltica.',
        englishTechnique: "Reliefs, golden acrylic, and asphalt paint.",
        price: 30000,
        // priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
        small: false
    },
    {
        id: 'profundidad-contemporanea',
        name: 'Profundidad Contemporánea',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea5.jpeg',
        description: 'Inspirada en mi obra Profundidad, realicé ésta pieza con relieves y el toque disrruptivo del color naranja que le aporta un toque contemporáneo. Combina tonos opacos y el detalle brillante del color champagne. \nEstá presentada en marco flotante de Kiri color natural.',
        englishDescription: "Inspired by my piece Depth, I created this work with reliefs and the disruptive touch of orange that adds a contemporary flair. It combines matte tones with the shiny detail of champagne color.\nIt is presented in a natural Kiri floating frame.",
        technique: 'Acrílicos y espátulas.',
        englishTechnique: "Acrylics and spatulas.",
        // price: 200000,
        // priceUsd: 20,
        size: '50 x 60 cm',
        dispo: false,
        small: false
    },
    {
        id: 'caminos',
        name: 'Caminos',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Caminos/Caminos1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Caminos/Caminos2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Caminos/Caminos3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Caminos/Caminos4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Caminos/Caminos5.jpeg',
        description: 'Jugar con los tonos, formas y profundidades resultó una fórmula perfecta para poner un toque de personalidad a cualquier ambiente. \nEstoy convencida de que los detalles marcan la diferencia, aportando una combinación de elegancia y modernidad.\nEstá presentada con marco flotante de Kiri color negro.\nCaminos fue expuesta en la muestra Percepciones en Galería Zero618.',
        englishDescription: "Playing with tones, shapes, and depths resulted in a perfect formula to add a touch of personality to any environment.\nI am convinced that details make a difference, providing a combination of elegance and modernity.\nIt is presented in a black Kiri floating frame.\nCaminos was exhibited in the Percepciones show at Gallery Zero618.",
        technique: 'Acrílicos y distintas espátulas.',
        englishTechnique: "Acrylics and various spatulas.",
        price: 200000,
        // priceUsd: 20,
        size: '60 x 80 cm',
        dispo: false,
        small: false
    },
    {
        id: 'libertad',
        name: 'Libertad',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Libertad/Libertad1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Libertad/Libertad2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Libertad/Libertad3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Libertad/Libertad4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Libertad/Libertad5.jpeg',
        description: 'Ésta obra, tal como lo dice su título, representa un momento de gran liberación, resultando muy poderosa e imponente.\nLa obra está presentada con marco flotante de Kiri color negro.',
        englishDescription: "This piece, as its title suggests (Freedom), represents a moment of great liberation, resulting in something very powerful and imposing.\nThe artwork is presented with a black kiri floating frame.",
        technique: 'Combina varias técnicas usando acrílicos sobre fondo en degradé.',
        englishTechnique: "It combines various techniques using acrylics on a gradient background.",
        price: 300000,
        // priceUsd: 20,
        size: '120 x 80 cm',
        dispo: false,
        small: false
    },
    {
        id: 'golden',
        name: 'Golden',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Golden/Golden1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Golden/Golden2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Golden/Golden3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Golden/Golden4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Golden/Golden5.jpeg',
        description: 'El dorado es una alta vibración que llena de energía a la persona que lo observa. Es un símbolo de poder y fortaleza.\nIdeal para lugares luminosos para disfrutar del brillo y destello así como para colocarlo en la entrada del hogar dando una sensación de energía poderosa. \nPresentado en marco flotante de Kiri natural acompañando el estilo del cuadro.',
        englishDescription: "Gold is a high vibration that energizes the person who observes it. It is a symbol of power and strength.\nIdeal for bright places to enjoy its shine and sparkle, as well as for placement at the entrance of a home to convey a sense of powerful energy.\nPresented in a natural Kiri floating frame, complementing the style of the piece. ",
        technique: 'Dorado con relieves y pintura asfáltica.',
        englishTechnique: "Gold with reliefs and asphalt paint.",
        // price: 250000,
        // priceUsd: 20,
        size: '30 x 40 cm',
        dispo: false,
        small: false
    },
    {
        id: 'destello',
        name: 'Destello',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Destello/Destello1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Destello/Destello2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Destello/Destello3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Destello/Destello4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Destello/Destello5.jpeg',
        description: 'El relieve de ésta obra provoca energía, invita a seguir una dirección, a entregarse al dinamismo. Y en el proceso, el resplandor nos permite sentir la intensidad de la luz, la provocación hacia la sensación del poder y la fuerza interior.\nLa obra se presenta con marco flotante de Kiri color negro.\nDestello fue expuesta en Cultura Viva.',
        englishDescription: "The relief of this artwork evokes energy, inviting one to follow a direction and surrender to dynamism. In the process, the brilliance allows us to feel the intensity of light, provoking a sense of power and inner strength.\nThe artwork is presented with a black kiri floating frame.\nDestello was exhibited at Cultura Viva.",
        technique: 'Acrílico, pasta de relieve y láminas de oro.',
        englishTechnique: "Acrylic, relief paste, and gold leaf.",
        // price: 250000,
        // priceUsd: 20,
        size: '50 x 50 cm',
        dispo: false,
        small: false
    },
    {
        id: 'noche-estrellada',
        name: 'La Noche Estrellada',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada5.jpeg',
        description: 'Una de mis grandes pasiones es la luna, y en ella me inspiré para hacer ésta obra que en finas líneas representa el color del cielo estrellado entrelazado con su color plateado.\nLa combinación de lo oscuro con el brillo aporta un detalle delicado para decorar cualquier ambiente.\nPresentada en marco flotante de Kiri color natural.\nLa Noche Estrellada fue expuesta en Galería Zero618.',
        englishDescription: "One of my greatest passions is the moon, and it inspired me to create this piece, which in fine lines represents the color of the starry sky intertwined with its silvery hue.\nThe combination of darkness with shine adds a delicate touch to decorate any space.\nPresented in a natural Kiri floating frame.\nLa Noche Estrellada was exhibited at Gallery Zero618.",
        technique: 'Acrílico.',
        englishTechnique: "Acrylics.",
        price: 170000,
        // priceUsd: 20,
        size: '50 x 50 cm',
        dispo: true,
        small: false
    },
    {
        id: 'percepcion',
        name: 'Percepción',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion/Percepcion1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion/Percepcion2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion/Percepcion3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion/Percepcion4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Percepcion/Percepcion5.jpeg',
        description: 'La importancia de entregarse a las sensaciones y a la forma en que la obra nos atraviesa.\nDonde algunos pueden ver y sentir la inmersión hacia el fondo, otros como yo podemos ver el impulso hacia el reflejo, la luz, la cima.\nÉsta obra invita a despertar los sentidos, apreciar los relieves, sentir la textura, ver la luz y la sombra.\nEstá presentada en marco flotante de Kiri negro.',
        englishDescription: "The importance of surrendering to sensations and the way the artwork moves through us.\nWhere some may see and feel the immersion into the depths, others like me can see the rise toward the reflection, the light, the peak.\nThis piece invites you to awaken your senses, appreciate the reliefs, feel the texture, and observe the light and shadow.\nIt is presented in a black Kiri floating frame.",
        technique: 'Acrílicos y Pasta de modelar.',
        englishTechnique: "Acrylics and modeling paste.",
        // price: 250000,
        // priceUsd: 20,
        size: '50 x 60 cm',
        dispo: false,
        small: false
    },
    {
        id: 'resplandor',
        name: 'El Resplandor',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElResplandor/ElResplandor1.jpeg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElResplandor/ElResplandor2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElResplandor/ElResplandor3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElResplandor/ElResplandor4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/ElResplandor/ElResplandor5.jpeg',
        description: 'Quiero compartir con vos ésta obra que disfruté mucho hacer.\nLa bauticé como 𝙀𝙡 𝙍𝙚𝙨𝙥𝙡𝙖𝙣𝙙𝙤𝙧 porque transmite mucha luz; no sólo por el brillo de sus láminas de cobre sino por todo lo que puse de mí al hacerlo.\nTiene todo para aportar personalidad a tu ambiente: relieve, brillo, toques de color y, sobre todo, carácter.\nEstá presentada con marco de Kiri flotante color negro.\nEl Resplandor fue expuesta en Cultura Viva y participa de la muestra Percepciones en Galería Zero618.',
        englishDescription: "I want to share with you this piece that I enjoyed creating so much.\nI named it 𝙀𝙡 𝙍𝙚𝙨𝙥𝙡𝙖𝙣𝙙𝙤𝙧 because it radiates a lot of light; not only from the shine of its copper sheets but also from everything I put into it while making it.\nIt has everything to add personality to your space: relief, shine, touches of color, and above all, character.\nIt is presented with a black kiri floating frame.\nEl Resplandor was exhibited at Cultura Viva and participates in the Percepciones show at Gallery Zero618.",
        technique: 'Acrílico, laminas de cobre, pintura asfaltica.',
        englishTechnique: "Acrylic, copper sheets, asphalt paint.",
        price: 200000,
        // priceUsd: 20,
        size: '60 x 80 cm',
        dispo: true,
        small: false
    },
    {
        id: 'tierra',
        name: 'Tierra',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Tierra/Tierra1.jpeg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Tierra/Tierra2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Tierra/Tierra3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Tierra/Tierra4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Tierra/Tierra5.jpeg',
        description: 'Te invito a usar todos los sentidos para disfrutar de esta pieza y dejarte llevar...\nGracias a los colores, el brillo y la magia de la textura es imposible no detenerse un largo rato descubriendo cada rincón de este cuadro.\nEs ideal para dar un toque distinguido y original a un ambiente de tu casa creando un punto focal que se completa con un marco flotante de Kiri natural.\nTierra participó de la muestra Percepciones en Galería Zero618.',
        englishDescription: "I invite you to use all your senses to enjoy this piece and let yourself be carried away...\nThanks to the colors, the shine, and the magic of the texture, it's impossible not to stop for a long time discovering every corner of this painting.\nIt's ideal for adding a distinguished and original touch to a space in your home, creating a focal point that is complemented by a natural Kiri floating frame.\nTierra participated in the Percepciones show at Gallery Zero618.",
        technique: 'Acrílicos y Pasta de modelar.',
        englishTechnique: "Acrylics and modeling paste.",
        price: 200000,
        // priceUsd: 20,
        size: '80 x 60 cm',
        dispo: false,
        small: false
    },
    {
        id: 'alma-revuelta',
        name: 'Alma Revuelta',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta2.jpg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta5.jpeg',
        description: 'El mar, como las personas, puede parecer calmo en su superficie. Pero en lo profundo, dentro de uno, dónde nadie lo vé, las aguas pueden estar embravecidas. Lo importante es no perder de vista el reflejo de la luz para encontrar el camino y lograr sentir serenidad.\nPresentado con marco flotante de Kiri en color negro\nAlma Revuelta participó de la muestra Percepciones en Galería Zero618.',
        englishDescription: "The sea, like people, may appear calm on the surface. But deep within, where no one sees, the waters can be tumultuous. What matters is not to lose sight of the reflection of light to find the way and achieve a sense of serenity.\nPresented in a black Kiri floating frame.\nAlma Revuelta participated in the Percepciones show at Gallery Zero618.",
        technique: 'Técnica mixta utilizando acrílicos con pincel y espátula y láminas de plata.',
        englishTechnique: "Mixed technique using acrylics with brush and spatula, and silver sheets.",
        // price: 250000,
        // priceUsd: 20,
        size: '50 x 50 cm',
        dispo: false,
        small: false
    },
    {
        id: 'esmeralda',
        name: 'Esmeralda',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esmeralda/Esmeralda1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esmeralda/Esmeralda2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esmeralda/Esmeralda3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esmeralda/Esmeralda4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Esmeralda/Esmeralda5.jpeg',
        description: 'Alguna vez te pasó de sentarte en un rincón de tu casa, ver una obra y sentir paz?\nBueno, eso es lo que ésta obra me transmite desde el primer momento creativo... Los distintos tonos turquesa y verde esmeralda y su movimiento me transportan al instante a un sentimiento de clara serenidad.\nSu color está relacionado con el crecimiento, el progreso, la naturaleza y la sanación; evocando también la tranquilidad y la paz.\nEnmarcado en madera flotante color negro.\nEsmeralda fue expuesta en Cultura Viva, Galería Zero618 y Palacio Barolo.',
        englishDescription: "Has there ever been a moment when you sat in a corner of your home, looked at a piece of art, and felt peace?\nWell, that’s what this piece has conveyed to me since the very first creative moment... The different turquoise and emerald green tones and their movement instantly transport me to a feeling of clear serenity.\nIts color is associated with growth, progress, nature, and healing, also evoking tranquility and peace.\nFramed in black floating wood.\nEsmeralda was exhibited at Cultura Viva, Gallery Zero618, and Palacio Barolo.",
        technique: 'Acrílicos.',
        englishTechnique: "Acrylics.",
        price: 400000,
        // priceUsd: 20,
        size: '80 x 120 cm',
        dispo: true,
        small: false
    },
    {
        id: 'espejo-marino',
        name: 'Espejo Marino',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino5.jpeg',
        description: 'Mi pasión por el mar y sus colores me inspiraron a crear ésta obra. Elegí su nombre porque imaginé estar debajo del agua, con la paz que da el silencio de estar bajo la superficie. Sus relieves, los cambios de color según la profundidad y los bloques de arena me devolvieron la imagen de un espejo del alma, con su abanico de emociones y sensaciones entre la luz y la oscuridad, la paz y la vorágine.\nSin dudas elegiría estar siempre rodeada del mar y sus colores. Es mi lugar en el mundo.\nObra enmarcada en Kiri flotante color negro.\nEspejo Marino participó de la muestra Percepciones en Galería Zero618.',
        englishDescription: "My passion for the sea and its colors inspired me to create this piece. I chose its name because I imagined being underwater, with the peace that comes from the silence beneath the surface. Its reliefs, the color changes according to depth, and the blocks of sand returned to me the image of a mirror of the soul, with its spectrum of emotions and sensations between light and darkness, peace and chaos.\nWithout a doubt, I would always choose to be surrounded by the sea and its colors. It is my place in the world.\nPiece framed in a black Kiri floating frame.\nEspejo Marino participated in the Percepciones show at Gallery Zero618.",
        technique: 'Acrílicos trabajados con espátulas para lograr texturas.',
        englishTechnique: "Acrylics worked with spatulas to achieve textures.",
        price: 150000,
        // priceUsd: 20,
        size: '50 x 60 cm',
        dispo: true,
        small: false
    },
    {
        id: 'reflejos',
        name: 'Reflejos',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Reflejos/Reflejos1.jpg',
        secondImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Reflejos/Reflejos2.jpeg',
        thirdImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Reflejos/Reflejos3.jpeg',
        fourthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Reflejos/Reflejos4.jpeg',
        fifthImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/Reflejos/Reflejos5.jpeg',
        description: 'Tal como la luna, la obra no tiene luz propia pero al recibir cualquier reflejo brilla con todo su esplendor. Un juego de relieves, texturas y materiales que provoca un resultado sin comparación.\nEs un cuadro ideal para colocar cerca de una ventana o un sector donde le de la luz ya que al utilizar acrílico color plata y hojas de aluminio el efecto es increíble.\nEstá presentada en marco flotante de Kiri color negro.\nReflejos fue expuesta en Palacio Barolo.',
        englishDescription: 'Just like the moon, the artwork does not have its own light, but when it receives any reflection, it shines in all its splendor. A play of reliefs, textures, and materials that creates an incomparable result.\nIt is an ideal piece to place near a window or an area where it receives light, as the use of silver acrylic and aluminum leaf creates an incredible effect.\nIt is presented in a black kiri floating frame.\nReflejos was exhibited at Palacio Barolo.',
        technique: 'Acrílicos, relieve y láminas de aluminio.',
        englishTechnique: 'Acrylics, relief, and aluminum sheets.',
        price: 150000,
        // priceUsd: 20,
        size: '40 x 30 cm',
        dispo: true,
        small: false
    }
]

