export const smallFormat = [
    {
        id: 'arena-dorada-small',
        name: 'Arena Dorada',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/ArenaDoradaChico/ArenaDorada.jpg',
        technique: 'Acrílicos, pasta de modelar y pintura asfáltica.',
        englishTechnique: 'Acrylics, modeling paste, and asphalt paint.',
        price: 30000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
        small: true
    },
    {
        id: 'percepcion-small',
        name: 'Percepción',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/PercepcionChico/PercepcionChico.jpg',
        technique: 'Acrílicos y pasta de modelar.',
        englishTechnique: 'Acrylics and modeling paste.',
        price: 35000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: false,
        small: true
    },
    {
        id: 'salpicre-small',
        name: 'Salpicré',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/Salpicre/Salpicre.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',
        price: 30000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
        small: true
    },
    {
        id: 'reflejos-negros-small',
        name: 'Reflejos Negro',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/ReflejosChico/ReflejosNegroChico.jpg',
        technique: 'Acrílicos y pasta de modelar.',
        englishTechnique: 'Acrylics and modeling paste.',
        price: 35000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
        small: true
    },
    {
        id: 'la-ola-small',
        name: 'La Ola',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/LaOlaChico/LaOla.jpg',
        technique: 'Acrílicos y relieves.',
        englishTechnique: 'Acrylics and reliefs.',        
        price: 35000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: false,
        small: true
    },
    {
        id: 'caida-aguamarina-small',
        name: 'Caída de Aguamarina',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/CaidaAguaMarina/CaidaAguaMarina.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 30000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: true,
        small: true
    },
    {
        id: 'paisaje-marino-small',
        name: 'Paisaje Marino',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/PaisajeMarino/PaisajeMarino.jpg',
        technique: 'Acrílicos, relieves y pintura asfáltica.',
        englishTechnique: 'Acrylics, reliefs, and asphalt paint.',        
        price: 35000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: true,
        small: true
    },
    {
        id: 'reflejos-negro-small',
        name: 'Reflejos Negro',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/ReflejosNegroRectangular/ReflejosNegroRectangular.jpg',
        technique: 'Acrílicos y pasta de modelar.',
        englishTechnique: 'Acrylics and modeling paste.',        
        price: 35000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: true,
        small: true
    },
    {
        id: 'relieves-costeros-small',
        name: 'Relieves Costeros',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/RelievesCosteros/RelievesCosteros.jpg',
        technique: 'Acrílicos, relieves y pintura asfaltica.',
        englishTechnique: 'Acrylics, reliefs, and asphalt paint.',        
        price: 35000,
        priceUsd: 20,
        size: '24 x 18 cm',
        dispo: true,
        small: true
    },
    {
        id: 'turmalina-small',
        name: 'Turmalina',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/RelievesCosteros/RelievesCosteros.jpg',
        technique: 'Acrílicos y relieves.',
        englishTechnique: 'Acrylics and reliefs.',        
        price: 45000,
        priceUsd: 20,
        size: '24 x 30 cm',
        dispo: true,
        small: true
    },
    {
        id: 'fondo-etereo-azul-chico-small',
        name: 'Fondo Etereo Azul Chico',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/EtereoChico/FotoEtereoChico.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 38000,
        priceUsd: 20,
        size: '24 x 30 cm',
        dispo: true,
        small: true
    },
    {
        id: 'fondo-etereo-verde-small',
        name: 'Fondo Etereo Verde',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/EtereoVerde/FotoEtereoVerde.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 40000,
        priceUsd: 20,
        size: '30 x 40 cm',
        dispo: true,
        small: true
    },
    {
        id: 'fondo-etereo-azul-small',
        name: 'Fondo Etereo Azul',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/Etereo/FotoEtereo.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 38000,
        priceUsd: 20,
        size: '24 x 30 cm',
        dispo: true,
        small: true
    },
]