export const smallFormat = [
    {
        id: 100,
        name: 'Arena Dorada',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/ArenaDoradaChico/ArenaDorada.jpg',
        technique: 'Acrílicos, pasta de modelar y pintura asfáltica.',
        englishTechnique: 'Acrylics, modeling paste, and asphalt paint.',
        price: 30000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
        small: true
    },
    {
        id: 101,
        name: 'Percepción',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/PercepcionChico/PercepcionChico.jpg',
        technique: 'Acrílicos y pasta de modelar.',
        englishTechnique: 'Acrylics and modeling paste.',
        price: 35000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: false,
        small: true
    },
    {
        id: 102,
        name: 'Salpicré',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/Salpicre/Salpicre.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',
        price: 30000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
        small: true
    },
    {
        id: 103,
        name: 'Reflejos Negro',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/ReflejosChico/ReflejosNegroChico.jpg',
        technique: 'Acrílicos y pasta de modelar.',
        englishTechnique: 'Acrylics and modeling paste.',
        price: 35000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
        small: true
    },
    {
        id: 104,
        name: 'La Ola',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/LaOlaChico/LaOla.jpg',
        technique: 'Acrílicos y relieves.',
        englishTechnique: 'Acrylics and reliefs.',        
        price: 35000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: true,
        small: true
    },
    {
        id: 105,
        name: 'Caida de Aguamarina',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/CaidaAguaMarina/CaidaAguaMarina.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 30000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: true,
        small: true
    },
    {
        id: 106,
        name: 'Paisaje Marino',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/PaisajeMarino/PaisajeMarino.jpg',
        technique: 'Acrílicos, relieves y pintura asfáltica.',
        englishTechnique: 'Acrylics, reliefs, and asphalt paint.',        
        price: 35000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: true,
        small: true
    },
    {
        id: 107,
        name: 'Reflejos Negro',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/ReflejosNegroRectangular/ReflejosNegroRectangular.jpg',
        technique: 'Acrílicos y pasta de modelar.',
        englishTechnique: 'Acrylics and modeling paste.',        
        price: 35000,
        priceUsd: 20,
        size: '18 x 24 cm',
        dispo: true,
        small: true
    },
    {
        id: 108,
        name: 'Relieves Costeros',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/RelievesCosteros/RelievesCosteros.jpg',
        technique: 'Acrílicos, relieves y pintura asfaltica.',
        englishTechnique: 'Acrylics, reliefs, and asphalt paint.',        
        price: 35000,
        priceUsd: 20,
        size: '24 x 18 cm',
        dispo: true,
        small: true
    },
    {
        id: 109,
        name: 'Turmalina',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/RelievesCosteros/RelievesCosteros.jpg',
        technique: 'Acrílicos y relieves.',
        englishTechnique: 'Acrylics and reliefs.',        
        price: 45000,
        priceUsd: 20,
        size: '24 x 30 cm',
        dispo: true,
        small: true
    },
    {
        id: 110,
        name: 'Fondo Etereo Azul Chico',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/EtereoChico/FotoEtereoChico.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 38000,
        priceUsd: 20,
        size: '24 x 30 cm',
        dispo: true,
        small: true
    },
    {
        id: 111,
        name: 'Fondo Etereo Verde',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/EtereoVerde/FotoEtereoVerde.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 40000,
        priceUsd: 20,
        size: '30 x 40 cm',
        dispo: true,
        small: true
    },
    {
        id: 112,
        name: 'Fondo Etereo Azul',
        principalImage: 'https://www.artesust.com.ar/ImageSabrinaRecortadas/FormatoPequenio/Etereo/FotoEtereo.jpg',
        technique: 'Acrílicos.',
        englishTechnique: 'Acrylics.',        
        price: 38000,
        priceUsd: 20,
        size: '24 x 30 cm',
        dispo: true,
        small: true
    },
]