export const data = [
    {
        id: 1,
        name: 'Turmalina',
        principalImage: "http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Turmalina/Turmalina1.jpg" ,
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Turmalina/Turmalina2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Turmalina/Turmalina3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Turmalina/Turmalina4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Turmalina/Turmalina5.jpeg',
        description: 'Inspirada en la piedra tan protectora, hice ésta obra poderosa que juega con relieves, reflejos y brillo. \n\n El negro es la ausencia de luz, y a la vez es la mezcla de todos los colores; transmite poder, formalidad, misterio, fuerza... Y si al negro lo cortamos con el dorado, que representa la luz, conseguimos un balance muy poderoso e interesante.\n Obra presentada con marco flotante de kiri color negro.',
        englishDescription: "Inspired by the protective nature of stone, I created this powerful piece that plays with reliefs, reflections, and shine. Black is the absence of light, yet it is also the combination of all colors; it conveys power, formality, mystery, strength... And when we cut through black with gold, which represents light, we achieve a very powerful and interesting balance.\n Piece presented in a black Kiri floating frame.",
        technique: 'Acrílicos',
        englishTechnique: 'Acrylics',
        price: 250000,
        priceUsd: 20,
        size: '50 x 60 cm',
        dispo: true,
    },
    {
        id: 2,
        name: 'Atardecer',
        principalImage: "http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Atardecer/Atardecer1.jpg",
        secondImage: "http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Atardecer/Atardecer2.jpeg",
        thirdImage: "http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Atardecer/atardecer3.jpeg",
        fifthImage: "http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Atardecer/Atardecer5.jpeg",
        description: 'Inspirada en la fuerza del atardecer fui creando ésta pequeña obra para traer un poco de esa poderosa sensación al interior del hogar.',
        englishDescription: "Inspired by the strength of the sunset, I created this small piece to bring a bit of that powerful sensation into the home. \nDue to its size, it can be placed on a shelf or desk, or hung from its floating frame.",
        technique: 'Juego de textura y degradé ',
        englishTechnique: 'Texture and gradient',
        price: 250000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
    },
    {
        id: 3,
        name: 'Profundidad',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Profundidad/Profundidad1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Profundidad/Profundidad2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Profundidad/Profundidad3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Profundidad/Profundidad4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Profundidad/Profundidad5.jpeg',
        description: 'Bauticé a ésta obra con su nombre porque como dice Shakespeare "Allí donde el agua alcanza su mayor profundidad se mantiene más en calma". \nLa realicé en un momento de mucha instrospección y sus colores fríos fundidos uno con el otro lo representan logrando un impacto muy especial. \n Presentado en marco flotante de Kiri color natural.',
        englishDescription: "I named this piece after Shakespeare’s quote, 'In the deepest water, the calmest stillness resides.' \nI created it during a time of deep introspection, and its cool colors blended into one another represent that, achieving a very special impact. \nPresented in a natural Kiri floating frame.",
        technique: 'Acrílicos',
        englishTechnique: 'Acrylics',
        price: 250000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
    },
    {
        id: 4,
        name: 'Eternidad',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Eternidad/Eternidad1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Eternidad/Eternidad2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Eternidad/Eternidad3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Eternidad/Eternidad4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Eternidad/Eternidad5.jpeg',
        description: 'Al momento de hacer ésta obra me inspiré en la vida, la tierra, lo eterno.\nPresentada en marco flotante de Kiri color natural.',
        englishDescription: "When creating this piece, I was inspired by life, the earth, and the eternal.\n Presented in a natural Kiri floating frame.",
        technique: 'Técnica mixta, relieves, acrílicos y pintura asfáltica.',
        englishTechnique: "Mixed techniques, reliefs, acrylics, and asphalt paint.",
        price: 250000,
        priceUsd: 20,
        size: '60 x 40 cm',
        dispo: true,
    },
    {
        id: 5,
        name: 'La Ola Magnetica',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/OlaMagnetica/OlaMagnetica5.jpeg',
        description: 'Quién no estuvo alguna vez en el mar y tuvo la oportunidad de ver ese rulo perfecto que se forma en la ola antes de romper con toda su bravura?. \nEn esta obra jugué con la textura y mis colores favoritos para transmitir esa hermosa sensación mezcla de adrenalina y admiración.\nPresentado en marco flotante de Kiri color negro.',
        englishDescription: "Who hasn't been to the sea at some point and had the chance to see that perfect curl that forms in the wave before it crashes with all its might?. \nIn this piece, I played with texture and my favorite colors to convey that beautiful sensation of a mix of adrenaline and admiration.\n Presented in a black Kiri floating frame.",
        technique: 'Realizada con pasta de modelar y acrílicos.',
        englishTechnique: "Made with modeling paste and acrylics.",
        price: 250000,
        priceUsd: 20,
        size: '40 x 60 cm',
        dispo: true,
    },
    {
        id: 6,
        name: 'Ritmo',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Ritmo/Ritmo1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Ritmo/Ritmo2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Ritmo/Ritmo3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Ritmo/Ritmo4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Ritmo/Ritmo5.jpeg',
        description: 'Una más de las obras en pequeño formato que me gusta hacer para destacar espacios. \nLa obra RITMO es una expresión de colores neutros y brillos que combinan y armonizan unos con otros. Brinda originalidad y distinción a cualquier espacio.\n Empotrado en marco flotante de Kiri color natural.',
        englishDescription: "Another one of the small-format pieces I enjoy creating to highlight spaces. \nThe piece RITMO is an expression of neutral colors and shines that blend and harmonize with one another. It adds originality and distinction to any space. \n Set in a natural Kiri floating frame.",
        technique: 'Realizada con pasta de modelar y acrílicos. ',
        englishTechnique: "Made with modeling paste and acrylics.",
        price: 250000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
    },
    {
        id: 7,
        name: 'El Cambio',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElCambio/ElCambio1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElCambio/ElCambio2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElCambio/ElCambio3.jpeg',
        // fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElCambio/ElCambio4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElCambio/ElCambio5.jpeg',
        description: 'Ésta obra la hice en un momento de cambio en mi vida, donde se abrían nuevas posibilidades, nuevos caminos, aparecían nuevas opciones y tomaba elecciones importantes.\nLo que a simple vista son sólo líneas, en realidad representan caminos cruzados, conexiones, uniones y opciones. Realizado en los colores con los que más disfruto trabajar, el resultado es un hermoso caos ordenado. \n Está empotrada en marco flotante de Kiri natural.',
        englishDescription: "I created this piece during a time of change in my life, when new possibilities were opening up, new paths were emerging, and I was making important choices. \n What may seem like mere lines at first glance actually represent crossed paths, connections, unions, and options. Made with the colors I enjoy working with the most, the result is a beautiful, ordered chaos.\n It is set in a natural Kiri floating frame.",
        technique: 'Acrílico',
        englishTechnique: "Acrylics",
        price: 250000,
        priceUsd: 20,
        size: '80 x 120 cm',
        dispo: true,
    },
    {
        id: 8,
        name: 'Trazos',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Trazos/Trazos1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Trazos/Trazos2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Trazos/Trazos3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Trazos/Trazos4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Trazos/Trazos5.jpeg',
        description: 'Tríptico en colores neutros. La simpleza de las líneas y sus colores dan un toque de estilo a cualquier ambiente.\nPueden decorar de forma individual o en conjunto. \nEstán presentados en marco flotante de Kiri color natural.',
        englishDescription: "Triptych in neutral colors. The simplicity of the lines and their colors add a touch of style to any environment. \nThey can be displayed individually or as a set. \nThey are presented in a natural Kiri floating frame.",
        technique: 'Acrílico',
        englishTechnique: "Acrylics",
        price: 250000,
        priceUsd: 20,
        size: '30 x 40 cm',
        dispo: true,
    },
    {
        id: 9,
        name: 'Arena Dorada',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ArenaDorada/ArenaDorada5.jpeg',
        description: 'Una obra pequeña para apoyar sobre un recibidor o colgarlo en algún espacio reducido que se busque destacar.\n Enmarcado en Kiri de color natural',
        englishDescription: "A small piece to place on a console table or hang in a compact space that you want to highlight.\n Framed in natural Kiri.",
        technique: 'Relieves, acrílico dorado y pintura asfáltica.',
        englishTechnique: "Reliefs, golden acrylic, and asphalt paint.",
        price: 250000,
        priceUsd: 20,
        size: '20 x 20 cm',
        dispo: true,
    },
    {
        id: 10,
        name: 'Profundidad Contemporánea',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ProfundidadContemporanea/ProfContemporanea5.jpeg',
        description: 'Inspirada en mi obra Profundidad, realicé ésta pieza con relieves y el toque disrruptivo del color naranja que le aporta un toque contemporáneo. Combina tonos opacos y el detalle brillante del color champagne. \nEstá presentada en marco flotante de Kiri color natural.',
        englishDescription: "Inspired by my piece Depth, I created this work with reliefs and the disruptive touch of orange that adds a contemporary flair. It combines matte tones with the shiny detail of champagne color.\nIt is presented in a natural Kiri floating frame.",
        technique: 'Acrílicos y espátulas.',
        englishTechnique: "Acrylics and spatulas.",
        price: 250000,
        priceUsd: 20,
        size: '50 x 60 cm',
        dispo: true,
    },
    {
        id: 11,
        name: 'Caminos',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Caminos/Caminos1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Caminos/Caminos2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Caminos/Caminos3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Caminos/Caminos4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Caminos/Caminos5.jpeg',
        description: 'Jugar con los tonos, formas y profundidades resultó una fórmula perfecta para poner un toque de personalidad a cualquier ambiente. \nEstoy convencida de que los detalles marcan la diferencia, aportando una combinación de elegancia y modernidad.\nEstá presentada con marco flotante de Kiri color negro.',
        englishDescription: "Playing with tones, shapes, and depths resulted in a perfect formula to add a touch of personality to any environment.\nI am convinced that details make a difference, providing a combination of elegance and modernity.\nIt is presented in a black Kiri floating frame.",
        technique: 'Acrílicos y distintas espátulas.',
        englishTechnique: "Acrylics and various spatulas.",
        price: 250000,
        priceUsd: 20,
        size: '60 x 80 cm',
        dispo: true,
    },
    {
        id: 12,
        name: 'Libertad',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Libertad/Libertad1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Libertad/Libertad2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Libertad/Libertad3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Libertad/Libertad4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Libertad/Libertad5.jpeg',
        description: 'Ésta obra, tal como lo dice su título, representa un momento de gran liberación, resultando muy poderosa e imponente.',
        englishDescription: "This piece, as its title suggests (Freedom), represents a moment of great liberation, resulting in something very powerful and imposing.",
        technique: 'Combina varias técnicas usando acrílicos sobre fondo en degradé.',
        englishTechnique: "It combines various techniques using acrylics on a gradient background.",
        price: 250000,
        priceUsd: 20,
        size: '120 x 80 cm',
        dispo: true,
    },
    {
        id: 13,
        name: 'Golden',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Golden/Golden1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Golden/Golden2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Golden/Golden3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Golden/Golden4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Golden/Golden5.jpeg',
        description: 'El dorado es una alta vibración que llena de energía a la persona que lo observa. Es un símbolo de poder y fortaleza.\nIdeal para lugares luminosos para disfrutar del brillo y destello así como para colocarlo en la entrada del hogar dando una sensación de energía poderosa. \nPresentado en marco flotante de Kiri natural acompañando el estilo del cuadro.',
        englishDescription: "Gold is a high vibration that energizes the person who observes it. It is a symbol of power and strength.\nIdeal for bright places to enjoy its shine and sparkle, as well as for placement at the entrance of a home to convey a sense of powerful energy.\nPresented in a natural Kiri floating frame, complementing the style of the piece. ",
        technique: 'Dorado con relieves y pintura asfáltica',
        englishTechnique: "Gold with reliefs and asphalt paint.",
        price: 250000,
        priceUsd: 20,
        size: '30 x 40 cm',
        dispo: true,
    },
    {
        id: 14,
        name: 'Destello',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Destello/Destello1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Destello/Destello2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Destello/Destello3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Destello/Destello4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Destello/Destello5.jpeg',
        description: 'Tal como la luna, la obra no tiene luz propia pero al recibir cualquier reflejo brilla con todo su esplendor. Un juego de relieves, texturas y materiales que provoca un resultado sin comparación.\nEs un cuadro ideal para colocar cerca de una ventana o un sector donde le de la luz ya que al utilizar acrílico color plata y hojas de aluminio el efecto es increíble.\nestá Presentada en marco flotante de Kiri color negro.',
        englishDescription: "Just like the moon, the piece has no light of its own, but when it catches any reflection, it shines in all its splendor. A play of reliefs, textures, and materials creates a result beyond comparison.\nIt's an ideal painting to place near a window or an area with light, as the use of silver acrylic and aluminum leaf creates an incredible effect.\nIt is presented in a black Kiri floating frame.",
        technique: 'Acrílico y hojas de aluminio',
        englishTechnique: "Acrylic and aluminum leaf.",
        price: 250000,
        priceUsd: 20,
        size: '40 x 30 cm',
        dispo: true
    },
    {
        id: 15,
        name: 'La Noche Estrellada',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/LaNocheEstrellada/NocheEstrellada5.jpeg',
        description: 'Una de mis grandes pasiones es la luna, y en ella me inspiré para hacer ésta obra que en finas líneas representa el color del cielo estrellado entrelazado con su color plateado.\nLa combinación de lo oscuro con el brillo aporta un detalle delicado para decorar cualquier ambiente.\nPresentada en marco flotante de Kiri color natural.',
        englishDescription: "One of my greatest passions is the moon, and it inspired me to create this piece, which in fine lines represents the color of the starry sky intertwined with its silvery hue.\nThe combination of darkness with shine adds a delicate touch to decorate any space.\nPresented in a natural Kiri floating frame.",
        technique: 'Acrílico',
        englishTechnique: "Acrylics",
        price: 250000,
        priceUsd: 20,
        size: '50 x 50 cm',
        dispo: true
    },
    {
        id: 16,
        name: 'Percepcion',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Percepcion/Percepcion1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Percepcion/Percepcion2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Percepcion/Percepcion3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Percepcion/Percepcion4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Percepcion/Percepcion5.jpeg',
        description: 'La importancia de entregarse a las sensaciones y a la forma en que la obra nos atraviesa.\nDonde algunos pueden ver y sentir la inmersión hacia el fondo, otros como yo podemos ver el impulso hacia el reflejo, la luz, la cima.\nÉsta obra invita a despertar los sentidos, apreciar los relieves, sentir la textura, ver la luz y la sombra.\nEstá presentada en marco flotante de Kiri negro.',
        englishDescription: "The importance of surrendering to sensations and the way the artwork moves through us.\nWhere some may see and feel the immersion into the depths, others like me can see the rise toward the reflection, the light, the peak.\nThis piece invites you to awaken your senses, appreciate the reliefs, feel the texture, and observe the light and shadow.\nIt is presented in a black Kiri floating frame.",
        technique: 'Acrilicos y Pasta de modelar',
        englishTechnique: "Acrylics and modeling paste.",
        price: 250000,
        priceUsd: 20,
        size: '50 x 60 cm',
        dispo: true
    },
    {
        id: 17,
        name: 'El Resplandor',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElResplandor/ElResplandor1.jpeg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElResplandor/ElResplandor2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElResplandor/ElResplandor3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElResplandor/ElResplandor4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/ElResplandor/ElResplandor5.jpeg',
        description: 'Quiero compartir con vos ésta obra que disfruté mucho hacer.\nLa bauticé como 𝙀𝙡 𝙍𝙚𝙨𝙥𝙡𝙖𝙣𝙙𝙤𝙧 porque transmite mucha luz; no sólo por el brillo de sus láminas de cobre sino por todo lo que puse de mí al hacerlo.\nTiene todo para aportar personalidad a tu ambiente: relieve, brillo, toques de color y, sobre todo, carácter.\nPuede enmarcarse con kiri flotante en color negro.',
        englishDescription: "I want to share with you this piece that I enjoyed creating so much.\nI named it 𝙀𝙡 𝙍𝙚𝙨𝙥𝙡𝙖𝙣𝙙𝙤𝙧 because it radiates a lot of light; not only from the shine of its copper sheets but also from everything I put into it while making it.\nIt has everything to add personality to your space: relief, shine, touches of color, and above all, character.\nIt can be framed with a black Kiri floating frame.",
        technique: 'Acrilico, laminas de cobre, pintura asfaltica',
        englishTechnique: "Acrylic, copper sheets, asphalt paint.",
        price: 250000,
        priceUsd: 20,
        size: '60 x 80 cm',
        dispo: true
    },
    {
        id: 18,
        name: 'Tierra',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Tierra/Tierra1.jpeg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Tierra/Tierra2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Tierra/Tierra3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Tierra/Tierra4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Tierra/Tierra5.jpeg',
        description: 'Te invito a usar todos los sentidos para disfrutar de esta pieza y dejarte llevar...\nGracias a los colores, el brillo y la magia de la textura es imposible no detenerse un largo rato descubriendo cada rincón de este cuadro.\nEs ideal para dar un toque distinguido y original a un ambiente de tu casa creando un punto focal que se completa con un marco flotante de Kiri natural.',
        englishDescription: "I invite you to use all your senses to enjoy this piece and let yourself be carried away...\nThanks to the colors, the shine, and the magic of the texture, it's impossible not to stop for a long time discovering every corner of this painting.\nIt's ideal for adding a distinguished and original touch to a space in your home, creating a focal point that is complemented by a natural Kiri floating frame.",
        technique: 'Acrilicos y Pasta de modelar',
        englishTechnique: "Acrylics and modeling paste.",
        price: 250000,
        priceUsd: 20,
        size: '80 x 60 cm',
        dispo: true
    },
    {
        id: 19,
        name: 'Alma Revuelta',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta2.jpg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/AlmaRevuelta/AlmaRevuelta5.jpeg',
        description: 'El mar, como las personas, puede parecer calmo en su superficie. Pero en lo profundo, dentro de uno, dónde nadie lo vé, las aguas pueden estar embravecidas. Lo importante es no perder de vista el reflejo de la luz para encontrar el camino y lograr sentir serenidad.\nPresentado con marco flotante de Kiri en color negro',
        englishDescription: "The sea, like people, may appear calm on the surface. But deep within, where no one sees, the waters can be tumultuous. What matters is not to lose sight of the reflection of light to find the way and achieve a sense of serenity.\nPresented in a black Kiri floating frame.",
        technique: 'Técnica mixta utilizando acrílicos con pincel y espátula y láminas de plata.',
        englishTechnique: "Mixed technique using acrylics with brush and spatula, and silver sheets.",
        price: 250000,
        priceUsd: 20,
        size: '50 x 50 cm',
        dispo: true
    },
    {
        id: 20,
        name: 'Esmeralda',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Esmeralda/Esmeralda1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Esmeralda/Esmeralda2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Esmeralda/Esmeralda3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Esmeralda/Esmeralda4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/Esmeralda/Esmeralda5.jpeg',
        description: 'Alguna vez te pasó de sentarte en un rincón de tu casa, ver una obra y sentir paz?\nBueno, eso es lo que ésta obra me transmite desde el primer momento creativo... Los distintos tonos turquesa y verde esmeralda y su movimiento me transportan al instante a un sentimiento de clara serenidad.\nSu color está relacionado con el crecimiento, el progreso, la naturaleza y la sanación; evocando también la tranquilidad y la paz.\nEnmarcado en madera flotante color negro.',
        englishDescription: "Has there ever been a moment when you sat in a corner of your home, looked at a piece of art, and felt peace?\nWell, that’s what this piece has conveyed to me since the very first creative moment... The different turquoise and emerald green tones and their movement instantly transport me to a feeling of clear serenity.\nIts color is associated with growth, progress, nature, and healing, also evoking tranquility and peace.\nFramed in black floating wood.",
        technique: 'Acrilico',
        englishTechnique: "Acrylics",
        price: 250000,
        priceUsd: 20,
        size: '80 x 120 cm',
        dispo: true
    },
    {
        id: 21,
        name: 'Espejo Marino',
        principalImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino1.jpg',
        secondImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino2.jpeg',
        thirdImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino3.jpeg',
        fourthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino4.jpeg',
        fifthImage: 'http://www.percepto.com.ar/Nahuel/ImageSabrinaRecortadas/EspejoMarino/EspejoMarino5.jpeg',
        description: 'Mi pasión por el mar y sus colores me inspiraron a crear ésta obra. Elegí su nombre porque imaginé estar debajo del agua, con la paz que da el silencio de estar bajo la superficie. Sus relieves, los cambios de color según la profundidad y los bloques de arena me devolvieron la imagen de un espejo del alma, con su abanico de emociones y sensaciones entre la luz y la oscuridad, la paz y la vorágine.\nSin dudas elegiría estar siempre rodeada del mar y sus colores. Es mi lugar en el mundo.\nObra enmarcada en Kiri flotante color negro.',
        englishDescription: "My passion for the sea and its colors inspired me to create this piece. I chose its name because I imagined being underwater, with the peace that comes from the silence beneath the surface. Its reliefs, the color changes according to depth, and the blocks of sand returned to me the image of a mirror of the soul, with its spectrum of emotions and sensations between light and darkness, peace and chaos.\nWithout a doubt, I would always choose to be surrounded by the sea and its colors. It is my place in the world.\nPiece framed in a black Kiri floating frame.",
        technique: 'Acrílicos trabajados con espátulas para lograr texturas',
        englishTechnique: "Acrylics worked with spatulas to achieve textures.",
        price: 250000,
        priceUsd: 20,
        size: '50 x 60 cm',
        dispo: true
    },

]

